name: Auto PR from main to publish

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: 'Merge main into publish'
          body: |
            This is an automated pull request to merge changes from `main` into `publish`.
            
            Please review the changes and merge if everything looks good.
          base: publish
          delete-branch: true
