name: Auto PR from main to publish

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: publish

      - name: Reset publish branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto/publish
          title: 'Release Version'
          body: |
            This is an automated pull request to merge changes from `main` into `publish`.
            
            Please review the changes and merge if everything looks good.
